services:
  db-florally:
    image: postgres:16.0
    container_name: db-florally
    environment:
      POSTGRES_DB: florally
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata_florally:/var/lib/postgresql/data
    ports:
      - "25432:5432"

volumes:
  pgdata_florally:
